### PR TITLE
Update SRP rates as of May 2024. Add flag for excluding solar plans

### PR DESCRIPTION
**Pull request by skunkworker**
Update SRP rates as of May 2024.
Add --exclude-solar-plans flag (useful if you don't use solar)

### CODE REVIEW

**Comment by theoldsport** [comment]
Wild, I was just about to submit the same PR, minus the new flag!

Despite the updated rates, there appears to be something off about the calculation. Or else SRP is exporting incorrect/imprecise usage data. Or else overcharging me.

**Comment by cheald** [comment]
Hey, thanks for this! Looks straightforward enough. There's a double assignment to plans in power.rb that needs to be cleaned up, but it looks like it's originally my fault. I'll clean it up and merge it; thank you!

**Comment by skunkworker** [comment]
> Wild, I was just about to submit the same PR, minus the new flag!
> 
> Despite the updated rates, there appears to be something off about the calculation. Or else SRP is exporting incorrect/imprecise usage data. Or else overcharging me. 

I agree, I copied the rates directly from their website a few days ago, and somehow the M-Power (I know I should switch) $ per kWh is like $0.015-ish higher than what I'm charged daily. (It might be the monthly connect cost smeared over the entire month?)

**Comment by theoldsport** [comment]
> (It might be the monthly connect cost smeared over the entire month?)

Definitely not the $20 service charge, you can take a look at my statement posted here https://github.com/cheald/srp-bill-calculator/issues/12, but nothing is obviously wrong with the script. I thought it might have something to do with weekend or holiday rates. The exported usage data does not perfectly match my statement's usage line item anyway, but even that can't account for the discrepancy.

**Pull request merged**
